version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      # - curl -sL https://rpm.nodesource.com/setup_20.x | sudo bash -
      # - sudo yum install -y nodejs
      - sudo yum install -y net-tools  # Adiciona o net-tools
      - node -v # Verifique a versão do Node.js.
  
  pre_build:
    commands:
      - echo "Listando o conteúdo atual do diretório:"
      - pwd
      - ls -la
      - echo "Tentando acessar o diretório chronos-alert..."
      - cd chronos-alert || { echo "Diretório 'chronos-alert' não encontrado!"; exit 1; }
      - ls -la 
      - echo "Fazendo pull do repositório..."
      - git pull origin main  
      - echo "Encerrando contêineres existentes no ambiente CodeBuild..."
      - docker-compose down || true
      - echo "Listando containers em execução..."
      - docker ps -a

  build:
    commands:
      - echo "Instalando dependências do frontend..."
      - cd client  # Acessa o diretório do frontend
      - yarn install 
      - echo "Dependências do frontend instaladas"
      - yarn build  # Gera os arquivos de build do frontend

      - echo "Instalando dependências do backend..."
      - cd ../server  # Acessa o diretório do backend
      - yarn install  # Instala as dependências do backend
      - echo "Dependências do backend instaladas"
  
      # # Construir e iniciar os containers Docker
      - echo "Construindo e iniciando containers Docker..."
      - cd ../  # Volta para o diretório chronos-alert
      - docker-compose up --build -d  # Executa o Docker Compose
  
  post_build:
    commands:
      - echo "Build completado com sucesso!"

artifacts:
  files:
    - '**/*'  # Inclui todos os arquivos gerados na construção
  base-directory: .  # Diretório raiz, inclui frontend / backend
  discard-paths: yes  # Descarta os caminhos para o upload mais simples.