version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - curl -sL https://rpm.nodesource.com/setup_20.x | sudo bash -
      - sudo yum install -y nodejs
      - node -v # Verifique a versão do Node.js.
  
  pre_build:
    commands:
      - echo "Fazendo pull do repositório..."
      - cd chronos-alert 
      - git pull origin main  
      - echo "Encerrando contêineres existentes..."
      - docker-compose down || true # Encerra os contêineres existentes, ignora erros

  build:
    commands:
      # Instalar dependências do frontend
      - echo "Instalando dependências do frontend..."
      - cd client  # Acessa o diretório do frontend
      - yarn install # Instala as dependências do frontend
      - echo "Dependências do frontend instaladas"
      - yarn build  # Gera os arquivos de build do frontend

      # # Instalar dependências do backend
      - echo "Instalando dependências do backend..."
      - cd ../server  # Acessa o diretório do backend
      - yarn install  # Instala as dependências do backend
      - echo "Dependências do backend instaladas"
  
      # # Construir e iniciar os containers Docker
      - echo "Construindo e iniciando containers Docker..."
      - cd ../  # Volta para o diretório chronos-alert
      - docker-compose up --build -d  # Executa o Docker Compose
  
  post_build:
    commands:
      - echo "Build completado com sucesso!"
