version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."

  pre_build:
    commands:
      - echo "Fazendo pull do repositório..."
      # Exibe os arquivos do diretório atual 
      - ls -l 
      # Acesse o diretório correto de forma relativa
      - echo "Tentando acessar ./chronos-alert..."
      # Usa o caminho relativo
      - cd chronos-alert || exit 1 
      # Exibe os arquivos no diretório chronos-alert
      - ls -l  
      # Verifica o estado do repositório git
      - git status  
      # Faz o pull do repositório
      - git pull origin main  

  build:
    commands:
      - echo "Instalando dependências NPM..."
      # Instala ou atualiza as dependências
      - npm install  
      - echo "Construindo e iniciando containers Docker..."
       # Executa o Docker Compose
      - docker-compose up --build -d 
