version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências..."

  pre_build:
    commands:
      - echo "Verificando diretório atual e fazendo pull do repositório..."
      - pwd  # Exibe o diretório atual
      - ls -l  # Lista os arquivos no diretório atual
      - git pull origin main  # Atualiza o repositório

  build:
    commands:
      - echo "Instalando dependências do frontend..."
      - cd client  # Navega até o diretório do frontend
      - npm install  # Instala as dependências do frontend
      - echo "Dependências do frontend instaladas com sucesso."

      - echo "Instalando dependências do backend..."
      - cd ../server  # Navega até o diretório do backend
      - npm install  # Instala as dependências do backend
      - echo "Dependências do backend instaladas com sucesso."

      - echo "Construindo os containers Docker..."
      - cd ..  # Volta para o diretório raiz (chronos-alert)
      - docker-compose up --build -d  # Constrói e sobe os containers
